/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ec.ups.edu.ec.Vista;

import ec.ups.edu.ec.Controlador.ControladorUsuario;
import ec.ups.edu.ec.Controlador.ControladorTelefono;
import ec.ups.edu.ec.Modelo.Telefono;
import ec.ups.edu.ec.Modelo.Usuario;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author ASUS
 */
public class Vtn_GestionTelefono extends javax.swing.JFrame {

    
    private ControladorUsuario controladorU;
    private ControladorTelefono controladorT;
    
    
    private Usuario usuario;
    private Telefono telefono;
    /**
     * Creates new form Vtn_GestionTelefono
     */
    public Vtn_GestionTelefono( ) {
        initComponents();
        
      
        
    }
    public void setUsuario(Usuario u) {
        this.usuario = u;
    }
    public void cargarCodigo() {
        int cd =  controladorT.cargarCodigo();
        txtCodigo.setText(String.valueOf(cd));
    }
    
    public void botonesInicio() {

        btnCrear.setEnabled(true);
       btnActualizar.setEnabled(false);
        btnEliminar.setEnabled(false);
    }

    public void botones() {

        btnCrear.setEnabled(false);
       btnActualizar.setEnabled(true);
        btnEliminar.setEnabled(true);
    }
    
    public void llenarTablaTelefono() {
        DefaultTableModel modeloTabla = (DefaultTableModel) tblTelefono.getModel();

        modeloTabla.setRowCount(0);
        for (Telefono tele : usuario.getListaTelefonos()) {
            Object[] rowData = {tele.getCodigo(), tele.getNumero(), tele.getTipo(), tele.getOperadora()};
            modeloTabla.addRow(rowData);
        }
        tblTelefono.setModel(modeloTabla);
    }
    
    public void limpiar() {
        txtCodigo.setText("");
        txtNumero.setText("");
        cbxTipo.setSelectedIndex(0);
        cbxOperadora.setSelectedIndex(0);
        btnCrear.setEnabled(true);
       btnActualizar.setEnabled(false);
        btnEliminar.setEnabled(false);
        cargarCodigo();
        tblTelefono.clearSelection();
        
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnActualizar = new javax.swing.JButton();
        btnEliminar = new javax.swing.JButton();
        btnCrear = new javax.swing.JButton();
        lbCodigo = new javax.swing.JLabel();
        btnBuscar = new javax.swing.JButton();
        lbTipo = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblTelefono = new javax.swing.JTable();
        lbNumero = new javax.swing.JLabel();
        lbOperadora = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        cbxTipo = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        cbxOperadora = new javax.swing.JComboBox<>();
        txtCodigo = new javax.swing.JTextField();
        txtNumero = new javax.swing.JTextField();

        btnActualizar.setBackground(new java.awt.Color(0, 51, 51));
        btnActualizar.setText("Actualizar");
        btnActualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnActualizarActionPerformed(evt);
            }
        });

        btnEliminar.setBackground(new java.awt.Color(0, 51, 51));
        btnEliminar.setText("Eliminar");
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActionPerformed(evt);
            }
        });

        btnCrear.setBackground(new java.awt.Color(0, 51, 51));
        btnCrear.setText("Crear");
        btnCrear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCrearActionPerformed(evt);
            }
        });

        lbCodigo.setText("Codigo: ");

        btnBuscar.setBackground(new java.awt.Color(0, 51, 51));
        btnBuscar.setText("Buscar");
        btnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarActionPerformed(evt);
            }
        });

        lbTipo.setText("Tipo: ");

        tblTelefono.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Codigo", "Tipo ", "Operadora", "Numero", "Cedula del dueño."
            }
        ));
        jScrollPane2.setViewportView(tblTelefono);

        lbNumero.setText("Numero:");

        lbOperadora.setText("Operadora: ");

        jLabel1.setFont(new java.awt.Font("Arial", 1, 10)); // NOI18N
        jLabel1.setText("*Recuerde que  para  actualizar y eliminar debera ingresar el codigo ");

        cbxTipo.setBackground(new java.awt.Color(102, 102, 255));
        cbxTipo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel2.setFont(new java.awt.Font("Agency FB", 2, 36)); // NOI18N
        jLabel2.setText("Gestion Telefonos.");

        cbxOperadora.setBackground(new java.awt.Color(102, 102, 255));
        cbxOperadora.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        txtCodigo.setBackground(new java.awt.Color(153, 153, 255));

        txtNumero.setBackground(new java.awt.Color(153, 153, 255));
        txtNumero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNumeroActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(62, 62, 62)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbCodigo)
                            .addComponent(lbTipo))
                        .addGap(73, 73, 73)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(cbxTipo, 0, 130, Short.MAX_VALUE)
                            .addComponent(txtCodigo)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(lbNumero)
                                .addGap(72, 72, 72))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lbOperadora)
                                .addGap(53, 53, 53)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtNumero, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cbxOperadora, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnActualizar, javax.swing.GroupLayout.DEFAULT_SIZE, 111, Short.MAX_VALUE)
                    .addComponent(btnEliminar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnBuscar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnCrear, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(47, 47, 47)
                .addComponent(jLabel2)
                .addGap(71, 71, 71))
            .addGroup(layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 702, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(13, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnCrear)
                            .addComponent(lbCodigo))
                        .addGap(12, 12, 12)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbTipo)
                            .addComponent(cbxTipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnActualizar))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(lbNumero)
                                    .addComponent(txtNumero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(cbxOperadora, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lbOperadora)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(3, 3, 3)
                                .addComponent(btnEliminar)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnBuscar))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(20, 20, 20)))
                .addGap(27, 27, 27)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtNumeroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNumeroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNumeroActionPerformed

    private void btnCrearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCrearActionPerformed
        // TODO add your handling code here:
         int codigo = Integer.parseInt(txtCodigo.getText());
        String numero = txtNumero.getText();
        String tipo = (String) cbxTipo.getSelectedItem();
        String operadora = (String) cbxOperadora.getSelectedItem();
        Telefono telefono = new Telefono(tipo, numero, tipo, operadora);

        if (numero.isEmpty() || tipo.equals("Seleccione una Opcion") || operadora.equals("Seleccione una Opcion")) {
            JOptionPane.showMessageDialog(this, "Llenar todos los campos");
        } else {
            controladorT.create(telefono);
            usuario.agregarTelefono(telefono);
            controladorU.actualizar(usuario, usuario);
            JOptionPane.showMessageDialog(this, "Teléfono creado con exito");
            llenarTablaTelefono();
            limpiar();
            System.out.println(usuario);
        }
    }//GEN-LAST:event_btnCrearActionPerformed

    private void btnActualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnActualizarActionPerformed
        // TODO add your handling code here:
        int codigo = Integer.parseInt(txtCodigo.getText());
        String numero = txtNumero.getText();
        String tipo = (String) cbxTipo.getSelectedItem();
        String operadora = (String) cbxOperadora.getSelectedItem();
        Telefono telefono = new Telefono(tipo, numero, tipo, operadora);

        if (numero.isEmpty() || tipo.equals("Seleccione una Opcion") || operadora.equals("Seleccione una Opcion")) {
            JOptionPane.showMessageDialog(this, "Llenar todos los campos");
        } else {
            controladorT.actualizar(telefono, telefono);
            usuario.actualizarTelefono(telefono);
            controladorU.actualizar(usuario, usuario);
            JOptionPane.showMessageDialog(this, "Teléfono actualizado correctamente");
            llenarTablaTelefono();
            limpiar();
        }
    }//GEN-LAST:event_btnActualizarActionPerformed

        
    private void tblTelefonosMouseClicked(java.awt.event.MouseEvent evt) {                                          
        int fila = tblTelefono.getSelectedRow();
        int cod = (int) tblTelefono.getValueAt(fila, 0);
        String num = (String) tblTelefono.getValueAt(fila, 1);
        String tipo = (String) tblTelefono.getValueAt(fila, 2);
        String opera = (String) tblTelefono.getValueAt(fila, 3);

        txtCodigo.setText(String.valueOf(cod));
        txtNumero.setText(num);
        cbxTipo.setSelectedItem(tipo);
        cbxOperadora.setSelectedItem(opera);
        botones();
    }
        
        
    private void formComponentHidden(java.awt.event.ComponentEvent evt) {                                     
        limpiar();

        DefaultTableModel modeloTabla = (DefaultTableModel) tblTelefono.getModel();
        modeloTabla.setRowCount(0);
        tblTelefono.setModel(modeloTabla);
    } 
                                                 
    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
        // TODO add your handling code here:
        controladorT.buscar(telefono);
    }//GEN-LAST:event_btnBuscarActionPerformed

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
        // TODO add your handling code here:
        int eliminar = JOptionPane.showConfirmDialog(this, "¿Seguro quieres eliminar este teléfono?");
        if(eliminar == JOptionPane.YES_OPTION){
            int codigo = Integer.parseInt(txtCodigo.getText());
            String numero = (String) txtNumero.getText();
            String tipo = (String) cbxTipo.getSelectedItem();
            String operadora = (String) cbxOperadora.getSelectedItem();
            Telefono telefono = new Telefono(tipo, numero, tipo, operadora);

            controladorT.eliminar(telefono);
            //usuario.eliminarTelefono(codigo);
            controladorU.actualizar(usuario, usuario);
            JOptionPane.showMessageDialog(this, "Teléfono eliminado con exito");
            llenarTablaTelefono();
            limpiar();
            System.out.println(usuario);
        }
            
    }//GEN-LAST:event_btnEliminarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnActualizar;
    private javax.swing.JButton btnBuscar;
    private javax.swing.JButton btnCrear;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JComboBox<String> cbxOperadora;
    private javax.swing.JComboBox<String> cbxTipo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lbCodigo;
    private javax.swing.JLabel lbNumero;
    private javax.swing.JLabel lbOperadora;
    private javax.swing.JLabel lbTipo;
    private javax.swing.JTable tblTelefono;
    private javax.swing.JTextField txtCodigo;
    private javax.swing.JTextField txtNumero;
    // End of variables declaration//GEN-END:variables
}
